<?xml version="1.0" encoding="utf-8"?>
<?AutomationStudio FileVersion="4.9"?>
<Program SubType="ANSIC" xmlns="http://br-automation.co.at/AS/Program">
  <Files>
    <File Description="Name the suite and add PVs for the program" Private="true">variables.var</File>
    <File>testSuite.c</File>
    <File Description="Auto generated code - list of all test sets in the program">autoGeneratedFile.c</File>
    <File>testSet_BallControl_Disabled.c</File>
    <File>testSet_BallControl_Initializing.c</File>
    <File>testSet_BallControl_Idle.c</File>
    <File>testSet_BallControl_Running.c</File>
    <File>testSet_BallControl_Stopping.c</File>
  </Files>
</Program>